site_name: Slack User Docs
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Workspace Setup : workspace_setup.md
  - Project Planning: project_planning.md
  - Zoom Integration: zoom_integration.md
  - Troubleshooting : trouble_shooting.md
  - Glossary : glossary.md
  
  
features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    # - navigation.path
    # - navigation.indexes
    # - navigation.sections
    # - navigation.sections
    # - navigation.expand
    # - toc.integrate
  navigation.instant
  navigation.instant.prefetch
  navigation.instant.progress
  navigation.tabs
  navigation.tabs.sticky
  navigation.tracking
  navigation.sections
  navigation.expand
  navigation.path
  navigation.indexes
  toc.follow
  toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
extra:
  collapse_toc: true

    