site_name: Slack User Documentation
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Instruction: instruction.md
  - Trouble Shooting : trouble_shooting.md
  - Glossary : glossary.md
  
features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.sections
    - navigation.expand
    - toc.integrate
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
    