site_name: Slack User Documentation
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md

  
features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.sections
markdown_extensions:
  - attr_list
  - md_in_html
    